Repository airbytehq/airbyte-python-cdk, pull requests merged in 2024-12, with the labels that each got.

#92 fix: add request count with eviction for not retriable requests to fix memory problem
  airbyte_cdk/sources/streams/http/http_client.py
  poetry.lock
  pyproject.toml
  unit_tests/sources/streams/http/test_http_client.py
Labels: bug, security

#100 ci: allow test matrix to always run, reporting success when skipped
  .github/workflows/pytest_matrix.yml
Labels: ci

#90 fix: ensure SDM image maintains airbyte-ci compatibility
  Dockerfile
Labels: bug, security

#101 ci: skip downstream connector tests if no source code is changed
  .github/workflows/connector-tests.yml
Labels: ci

#99 ci: run airbyte connector tests from master branch
  .github/workflows/connector-tests.yml
Labels: ci

#95 chore(documentation): Fix header for CDK migration 6.0.0
  cdk-migrations.md
Labels: chore

#102 ci: reorder job steps
  .github/workflows/connector-tests.yml
Labels: ci

#50 feat: add download_decoder + download_extractor
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/extractors/response_to_file_extractor.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/requesters/http_job_repository.py
  unit_tests/sources/declarative/extractors/test_response_to_file_extractor.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/requesters/test_http_job_repository.py
Labels: enhancement

#96 feat(concurrent): [ISSUE #10550] do not raise when record does not have cursor value in…
  airbyte_cdk/sources/streams/concurrent/cursor.py
  unit_tests/sources/streams/concurrent/test_cursor.py
Labels: enhancement

#89 feat(Low-Code Concurrent CDK): Allow non-incremental substreams and list based partition router streams with parents to be processed by the concurrent cdk
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/streams/concurrent/default_stream.py
  unit_tests/sources/declarative/decoders/test_json_decoder.py
  unit_tests/sources/declarative/test_concurrent_declarative_source.py
  unit_tests/sources/streams/concurrent/scenarios/stream_facade_scenarios.py
  unit_tests/sources/streams/concurrent/scenarios/thread_based_concurrent_stream_scenarios.py
  unit_tests/sources/streams/concurrent/test_default_stream.py
Labels: enhancement

#107 ci: create unified cdk, sdm, and builder publish flow
  .github/workflows/publish_sdm_connector.yml
  .github/workflows/pypi_publish.yml
  .github/workflows/pytest_fast.yml
Labels: ci

#109 ci: Don't bump Connector Builder to prerelease CDK versions
  .github/workflows/pypi_publish.yml
Labels: ci

#103 fix: gracefully continue on tempfile cleanup failure
  airbyte_cdk/entrypoint.py
  unit_tests/sources/streams/test_call_rate.py
Labels: bug, security

#61 feat(low-code concurrent): [ISSUE #10550] have streams without partition routers nor cursor run …
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/streams/concurrent/helpers.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/test_concurrent_declarative_source.py
  unit_tests/sources/streams/concurrent/test_helpers.py
Labels: enhancement

#120 docs: updated readme, contributing, and release docs
  README.md
  docs/CONTRIBUTING.md
  docs/RELEASES.md
  pyproject.toml
Labels: docs

#122 ci: auto-publish sdm for each release
  .github/workflows/pypi_publish.yml
Labels: ci

#124 ci: dont create builder pr if sdm publish fails
  .github/workflows/pypi_publish.yml
Labels: ci

#88 feat(low-code cdk): add component resolver and http component resolver
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/manifest_component_transformer.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/partition_routers/__init__.py
  airbyte_cdk/sources/declarative/resolvers/__init__.py
  airbyte_cdk/sources/declarative/resolvers/components_resolver.py
  airbyte_cdk/sources/declarative/resolvers/http_components_resolver.py
  unit_tests/sources/declarative/resolvers/__init__.py
  unit_tests/sources/declarative/resolvers/test_http_components_resolver.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
Labels: enhancement

#135 chore: fix typing issues
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
Labels: chore

#138 ci: fix CI reports not uploading
  .github/workflows/connector-tests.yml
Labels: ci

#140 ci: add `poetry check` step
  .github/workflows/pytest_fast.yml
Labels: ci

#141 ci: update pytest workflow to trigger on all pull requests, including forks
  .github/workflows/pytest_matrix.yml
Labels: ci

#130 fix(concurrent-cdk): Move the grouping of concurrent and synchronous streams into the read and discover commands instead of when initializing the source
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  unit_tests/sources/declarative/decoders/test_json_decoder.py
  unit_tests/sources/declarative/test_concurrent_declarative_source.py
Labels: bug

#131 ci: update connector-tests.yml worfklow to use dev binary of airbyte-ci
  .github/workflows/connector-tests.yml
Labels: ci

#143 chore: update SDM image to be rootless
  Dockerfile
Labels: chore

#145 chore: revert SDM image change
  Dockerfile
Labels: chore

#153 ci: make it easier to find the connector test report url upon failure
  .github/workflows/connector-tests.yml
Labels: ci

#154 ci: add `poe install` definition to save some keystrokes
  pyproject.toml
Labels: ci

#146 fix(concurrent): Reduce occurrences of database table is locked errors
  airbyte_cdk/sources/streams/http/http_client.py
Labels: bug

#148 fix(concurrent): Ensure default concurrency level does not generate deadlock
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
Labels: bug

#147 chore: make SDM image rootless
  Dockerfile
Labels: chore

#157 docs: add SDM release troubleshooting info
  docs/RELEASES.md
Labels: docs

#159 ci: change dependabot github actions to monthly
  .github/dependabot.yml
Labels: ci

#121 feat: add unit test fixtures for manifest-only connectors to CDK
  airbyte_cdk/test/utils/manifest_only_fixtures.py
Labels: enhancement

#104 feat(low-code cdk): add dynamic schema loader
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/manifest_component_transformer.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/schema/__init__.py
  airbyte_cdk/sources/declarative/schema/dynamic_schema_loader.py
  unit_tests/sources/declarative/schema/test_dynamic_schema_loader.py
Labels: enhancement

#149 feat(low-code cdk): add config component resolver
  airbyte_cdk/sources/declarative/auth/selective_authenticator.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/manifest_component_transformer.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/resolvers/__init__.py
  airbyte_cdk/sources/declarative/resolvers/config_components_resolver.py
  unit_tests/sources/declarative/resolvers/test_config_components_resolver.py
  unit_tests/sources/declarative/resolvers/test_http_components_resolver.py
Labels: enhancement

#172 fix: (Low-Code) (DeclarativeOAuthFlow) - fix `tooltip examples` and `labels` representation to show values instead of full object
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
Labels: bug, security

#178 feat(low-code cdk): add KeyToSnakeCase transformation
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/transformations/keys_to_snake_transformation.py
  poetry.lock
  pyproject.toml
  unit_tests/sources/declarative/transformations/test_keys_to_lower_transformation.py
  unit_tests/sources/declarative/transformations/test_keys_to_snake_transformation.py
Labels: enhancement

#171 fix: (HttpClient) rate limit fix unlimited tries
  airbyte_cdk/sources/streams/http/http_client.py
  unit_tests/sources/streams/http/test_http_client.py
Labels: bug

#181 feat(low-code cdk): add flatten fields
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/transformations/flatten_fields.py
  unit_tests/sources/declarative/transformations/test_flatten_fields.py
Labels: enhancement

#176 feat(low-code cdk): add transformation to dynamic schema loader
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/schema/dynamic_schema_loader.py
  unit_tests/sources/declarative/schema/test_dynamic_schema_loader.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
Labels: enhancement

#170 fix(Low-Code Concurrent CDK): Refactor the low-code AsyncRetriever to use an underlying StreamSlicer
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/partition_routers/__init__.py
  airbyte_cdk/sources/declarative/partition_routers/async_job_partition_router.py
  airbyte_cdk/sources/declarative/retrievers/async_retriever.py
  unit_tests/sources/declarative/async_job/test_integration.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/partition_routers/test_async_job_partition_router.py
Labels: bug

#175 feat(HttpComponentsResolver): added stream slices to HttpComponentsResolver
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/resolvers/http_components_resolver.py
  unit_tests/sources/declarative/resolvers/test_http_components_resolver.py
Labels: enhancement

#182 fix: (DeclarativeOAuthFlow) - allow `DeclarativeOauth2Authenticator` to use `access_token` directly when no `token_refresh_endpoint` or `refresh_token` values are provided.
  airbyte_cdk/sources/declarative/auth/oauth.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
  unit_tests/sources/declarative/auth/test_oauth.py
Labels: bug, security, oauth, declarative_oauth, oauth_in_builder

#186 fix: (DeclarativeOAuthFlow) - fix the bug when `refresh_token` is not provided from the `test` authentication
  airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
Labels: bug, security

#189 fix: fix sorting & __init__ imports
  airbyte_cdk/__init__.py
  airbyte_cdk/cli/source_declarative_manifest/__init__.py
  airbyte_cdk/models/__init__.py
  airbyte_cdk/sources/declarative/async_job/job_orchestrator.py
  airbyte_cdk/sources/declarative/auth/__init__.py
  airbyte_cdk/sources/declarative/decoders/__init__.py
  airbyte_cdk/sources/declarative/extractors/__init__.py
  airbyte_cdk/sources/declarative/incremental/__init__.py
  airbyte_cdk/sources/declarative/partition_routers/__init__.py
  airbyte_cdk/sources/declarative/requesters/error_handlers/__init__.py
  airbyte_cdk/sources/declarative/requesters/error_handlers/backoff_strategies/__init__.py
  airbyte_cdk/sources/declarative/requesters/paginators/__init__.py
  airbyte_cdk/sources/declarative/requesters/paginators/strategies/__init__.py
  airbyte_cdk/sources/declarative/requesters/request_options/__init__.py
  airbyte_cdk/sources/declarative/resolvers/__init__.py
  airbyte_cdk/sources/declarative/retrievers/__init__.py
  airbyte_cdk/sources/declarative/retrievers/async_retriever.py
  airbyte_cdk/sources/declarative/schema/__init__.py
  airbyte_cdk/sources/file_based/availability_strategy/__init__.py
  airbyte_cdk/sources/file_based/discovery_policy/__init__.py
  airbyte_cdk/sources/file_based/file_types/__init__.py
  airbyte_cdk/sources/file_based/schema_validation_policies/__init__.py
  airbyte_cdk/sources/file_based/stream/concurrent/cursor/__init__.py
  airbyte_cdk/sources/message/__init__.py
  airbyte_cdk/sources/streams/__init__.py
  airbyte_cdk/sources/streams/checkpoint/__init__.py
  airbyte_cdk/sources/streams/http/__init__.py
  airbyte_cdk/sources/streams/http/error_handlers/__init__.py
  airbyte_cdk/test/mock_http/__init__.py
  airbyte_cdk/test/mock_http/mocker.py
  airbyte_cdk/test/mock_http/response_builder.py
  airbyte_cdk/utils/__init__.py
  pyproject.toml
  unit_tests/sources/declarative/resolvers/test_http_components_resolver.py
  unit_tests/sources/mock_server_tests/test_helpers/__init__.py
Labels: bug, security

#179 feat: add Composite Raw Decoder
  .github/workflows/pypi_publish.yml
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/decoders/__init__.py
  airbyte_cdk/sources/declarative/decoders/composite_raw_decoder.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/decoders/test_composite_decoder.py
  unit_tests/sources/declarative/decoders/test_decoders_memory_usage.py
  unit_tests/sources/declarative/decoders/test_json_decoder.py
Labels: enhancement
