Repository airbytehq/airbyte-python-cdk, pull requests merged in 2024-11, with the labels that each got.

#2 CI: Add GitHub workflows, including testing, linting, release drafting, and documentation generation
  .github/dependabot.yml
  .github/release-drafter.yml
  .github/workflows/connector-tests.yml
  .github/workflows/fix-pr-command.yml
  .github/workflows/pdoc_preview.yml
  .github/workflows/pdoc_publish.yml
  .github/workflows/poetry-lock-command.yml
  .github/workflows/pypi_publish.yml
  .github/workflows/python_lint.yml
  .github/workflows/python_pytest.yml
  .github/workflows/release_drafter.yml
  .github/workflows/semantic_pr_check.yml
  .github/workflows/slash_command_dispatch.yml
  .github/workflows/test-pr-command.yml
  .gitignore
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
  poetry.lock
  pyproject.toml
Labels: ci

#16 chore: resolve ruff lint issues
  airbyte_cdk/models/airbyte_protocol.py
  airbyte_cdk/models/well_known_types.py
  airbyte_cdk/sources/declarative/datetime/min_max_datetime.py
  airbyte_cdk/sources/file_based/file_types/csv_parser.py
  airbyte_cdk/sources/file_based/file_types/excel_parser.py
  pyproject.toml
  unit_tests/sources/streams/concurrent/test_concurrent_read_processor.py
  unit_tests/test/mock_http/test_mocker.py
Labels: chore

#17 chore: apply Prettier auto-formatting to codebase
  .github/release-drafter.yml
  .github/workflows/autofix-command.yml
  .github/workflows/connector-tests.yml
  .github/workflows/pdoc_preview.yml
  .github/workflows/pdoc_publish.yml
  .github/workflows/poetry-lock-command.yml
  .github/workflows/pypi_publish.yml
  .github/workflows/python_lint.yml
  .github/workflows/python_pytest.yml
  .github/workflows/slash_command_dispatch.yml
  .github/workflows/test-command.yml
  CHANGELOG.md
  cdk-migrations.md
  sphinx-docs.md
Labels: chore

#18 CI: Fix mypy script reference to main branch
  bin/run-mypy-on-modified-files.sh
Labels: ci

#23 Chore: Delete duplicate project file
  pyproject.toml-bak
Labels: bug, security

#24 chore: use dynamic versioning
  .github/workflows/connector-tests.yml
  .github/workflows/pypi_publish.yml
  airbyte_cdk/__init__.py
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  poetry.lock
  pyproject.toml
Labels: chore

#25 docs: link to release notes from changelog
  CHANGELOG.md
Labels: docs

#27 chore: update dependabot rules
  .github/dependabot.yml
Labels: chore

#26 CI: update test workflows
  .github/workflows/connector-tests.yml
  .github/workflows/pytest_fast.yml
  .github/workflows/pytest_matrix.yml
  pyproject.toml
Labels: ci

#36 ci: fix trailing double quote issue
  .github/workflows/connector-tests.yml
Labels: ci

#31 feat(airbyte-cdk): update datamodel_code_generator to `0.26.3`
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  bin/generate_component_manifest_files.py
Labels: enhancement

#40 ci: use new `--use-local-cdk` method for testing connectors
  .github/workflows/connector-tests.yml
  airbyte_cdk/__init__.py
Labels: ci

#42 ci: replace faker with hardcoded source
  .github/workflows/connector-tests.yml
Labels: ci

#45 fix(airbyte-cdk): Fix Record Filter Validation in ConcurrentDeclarativeSource
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
Labels: bug

#48 ci: fix version ref in github publish action
  .github/workflows/pypi_publish.yml
Labels: ci

#20 feat(airbyte-cdk): add gzipjson decoder
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/decoders/__init__.py
  airbyte_cdk/sources/declarative/decoders/json_decoder.py
  airbyte_cdk/sources/declarative/migrations/legacy_to_per_partition_state_migration.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/decoders/test_json_decoder.py
Labels: enhancement

#32 chore(refactor): Remove Partition.close
  airbyte_cdk/sources/concurrent_source/concurrent_read_processor.py
  airbyte_cdk/sources/file_based/stream/concurrent/adapters.py
  airbyte_cdk/sources/streams/concurrent/adapters.py
  airbyte_cdk/sources/streams/concurrent/partitions/partition.py
  unit_tests/sources/file_based/stream/concurrent/test_adapters.py
  unit_tests/sources/file_based/stream/concurrent/test_file_based_concurrent_cursor.py
  unit_tests/sources/streams/concurrent/test_adapters.py
  unit_tests/sources/streams/concurrent/test_concurrent_read_processor.py
Labels: chore

#39 chore(refactor): refactor partition generator to take any stream slicer
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/stream_slicers/declarative_partition_generator.py
  airbyte_cdk/sources/declarative/stream_slicers/stream_slicer.py
  airbyte_cdk/sources/streams/concurrent/adapters.py
  airbyte_cdk/sources/streams/concurrent/cursor.py
  airbyte_cdk/sources/streams/concurrent/partitions/stream_slicer.py
  airbyte_cdk/sources/streams/concurrent/state_converters/abstract_stream_state_converter.py
  airbyte_cdk/utils/slice_hasher.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/stream_slicers/test_declarative_partition_generator.py
  unit_tests/sources/streams/concurrent/test_adapters.py
  unit_tests/sources/streams/concurrent/test_cursor.py
Labels: chore

#51 chore(deps): bump nltk from 3.8.1 to 3.9.1 fix unit tests for dependabot/pip/nltk-3.9 branch
  .gitignore
  airbyte_cdk/sources/file_based/file_types/unstructured_parser.py
Labels: dependencies, chore

#38 fix(manifest-connectors): resolve parsing errors during version comparisons
  .github/workflows/connector-tests.yml
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
Labels: bug, ci

#58 Feat: Incorporate SDM in CDK and add publish workflow
  .github/workflows/cdk-publish.yml
  .github/workflows/connector-tests.yml
  Dockerfile
  airbyte_cdk/cli/__init__.py
  airbyte_cdk/cli/source_declarative_manifest/__init__.py
  airbyte_cdk/cli/source_declarative_manifest/_run.py
  airbyte_cdk/cli/source_declarative_manifest/spec.json
  poetry.lock
  pyproject.toml
Labels: enhancement

#68 chore(deps): bump `jsonschema` to "~4.17.3"
  poetry.lock
  pyproject.toml
Labels: dependencies, chore

#74 fix: set interpolation macro/filter titles to match the actual function name
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
Labels: bug, security

#77 fix: combined publish flow for CDK/SDM
  .github/workflows/cdk-publish.yml
  .github/workflows/pypi_publish.yml
  Dockerfile
Labels: bug, security

#78 ci: add environment declaration for DockerhHub publish
  .github/workflows/pypi_publish.yml
Labels: ci

#81 ci: disable SDM publish step
  .github/workflows/pypi_publish.yml
Labels: ci

#83 CI: move SDM image publish to dedicated step
  .github/workflows/publish_sdm_connector.yml
  .github/workflows/pypi_publish.yml
Labels: ci

#84 fix: update source-declarative-manifest entrypoint
  Dockerfile
Labels: bug, security

#87 feat: (Airbyte Python CDK) - extend the `error_message` info for the `ResponseAction.FAIL` request scenario
  README.md
  airbyte_cdk/sources/streams/http/http_client.py
  unit_tests/sources/streams/http/test_http.py
Labels: enhancement
