Repository airbytehq/airbyte-python-cdk, pull requests merged in 2025-07, with the labels that each got.

#633 feat: make use_parent_params configurable
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  unit_tests/sources/declarative/parsers/test_manifest_component_transformer.py
Labels: enhancement

#643 ci: temporarily remove source-amplitude from CDK connector tests
  .github/workflows/connector-tests.yml
Labels: ci

#628 chore: add unidecode dep to python CDK
  poetry.lock
  pyproject.toml
Labels: chore

#637 fix: properly set token_expiry_is_time_of_expiration and mask access token when logging
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
Labels: bug, security

#638 feat(property-chunking): Allow the definition of query_properties on the HttpRequester component
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
Labels: enhancement

#651 chore: Update source-declarative-manifest to use python-connector-base 4.0.2
  Dockerfile
Labels: chore

#635 chore: reorder inject_into in RequestOption and fix title and description in refresh token updater
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
Labels: chore

#653 feat: support custom config transformations
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/transformations/config_transformations/test_custom_config_transformation.py
Labels: enhancement

#649 fix(low-code cdk): Add literal type for ConfigNormalizationRules components
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
Labels: bug

#658 fix: add array type to field_pointers items
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
Labels: bug, security

#659 fix: add interpolation_context to auth fields
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
Labels: bug, security

#654 fix: fast tests conditionally skip streams
  airbyte_cdk/test/entrypoint_wrapper.py
  airbyte_cdk/test/models/scenario.py
  airbyte_cdk/test/standard_tests/connector_base.py
  airbyte_cdk/test/standard_tests/docker_base.py
  airbyte_cdk/test/standard_tests/source_base.py
  airbyte_cdk/utils/connector_paths.py
Labels: bug, security, team/python-connectors, testing

#661 chore: update descriptions and examples of complex fields
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
Labels: chore

#665 fix: class AirbyteOutputException initialization
  airbyte_cdk/test/entrypoint_wrapper.py
Labels: bug, security

#676 fix: make builder test read work when a mix of static and dynamic streams are passed in
  airbyte_cdk/connector_builder/connector_builder_handler.py
  airbyte_cdk/connector_builder/test_reader/helpers.py
  airbyte_cdk/connector_builder/test_reader/message_grouper.py
  airbyte_cdk/connector_builder/test_reader/reader.py
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/connector_builder/test_message_grouper.py
Labels: bug, security

#674 chore: remove cursor.is_greater_than_or_equal
  airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py
  airbyte_cdk/sources/declarative/incremental/global_substream_cursor.py
  airbyte_cdk/sources/declarative/incremental/per_partition_cursor.py
  airbyte_cdk/sources/declarative/incremental/per_partition_with_global.py
  airbyte_cdk/sources/declarative/incremental/resumable_full_refresh_cursor.py
  airbyte_cdk/sources/declarative/retrievers/simple_retriever.py
  airbyte_cdk/sources/streams/checkpoint/cursor.py
  airbyte_cdk/sources/streams/checkpoint/resumable_full_refresh_cursor.py
  airbyte_cdk/sources/streams/checkpoint/substream_resumable_full_refresh_cursor.py
  unit_tests/sources/declarative/incremental/test_datetime_based_cursor.py
  unit_tests/sources/declarative/incremental/test_per_partition_cursor.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
Labels: chore
