Repository airbytehq/airbyte-python-cdk, pull requests merged in 2025-02, with the labels that each got.

#305 fix(low-code): add wrong dynamic stream name type validation
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  unit_tests/sources/declarative/resolvers/test_http_components_resolver.py
Labels: bug

#307 feat(low-code): improve logging on async retriever errors
  airbyte_cdk/sources/declarative/async_job/job_orchestrator.py
Labels: enhancement

#313 chore: use python 3.11 for connector tests in CI
  .github/workflows/connector-tests.yml
Labels: chore

#201 feat: enable handling of nested fields when injecting request_option in request body_json
  airbyte_cdk/sources/declarative/auth/token.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/partition_routers/list_partition_router.py
  airbyte_cdk/sources/declarative/partition_routers/substream_partition_router.py
  airbyte_cdk/sources/declarative/requesters/http_requester.py
  airbyte_cdk/sources/declarative/requesters/paginators/default_paginator.py
  airbyte_cdk/sources/declarative/requesters/request_option.py
  airbyte_cdk/sources/declarative/requesters/request_options/datetime_based_request_options_provider.py
  airbyte_cdk/sources/declarative/retrievers/simple_retriever.py
  airbyte_cdk/utils/mapping_helpers.py
  unit_tests/sources/declarative/auth/test_token_auth.py
  unit_tests/sources/declarative/incremental/test_datetime_based_cursor.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/requesters/paginators/test_default_paginator.py
  unit_tests/sources/declarative/requesters/request_options/test_request_options.py
  unit_tests/sources/declarative/requesters/test_http_requester.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
  unit_tests/utils/test_mapping_helpers.py
Labels: enhancement

#322 fix(low-code): Add parent state migration from global state
  airbyte_cdk/sources/declarative/partition_routers/substream_partition_router.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
  unit_tests/sources/declarative/partition_routers/test_substream_partition_router.py
Labels: bug

#324 feat(OAuth): allow for access_token without expiration from the API
  airbyte_cdk/sources/declarative/auth/oauth.py
  airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
  unit_tests/sources/declarative/auth/test_oauth.py
Labels: enhancement

#316 fix: (low code)run state migrations for concurrent streams
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/custom_state_migration.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/test_concurrent_declarative_source.py
Labels: bug, security

#326 chore(decoder): clean decoders and make csvdecoder available
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/decoders/__init__.py
  airbyte_cdk/sources/declarative/decoders/composite_raw_decoder.py
  airbyte_cdk/sources/declarative/decoders/json_decoder.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/auth/test_token_provider.py
  unit_tests/sources/declarative/decoders/test_composite_decoder.py
  unit_tests/sources/declarative/decoders/test_decoders_memory_usage.py
  unit_tests/sources/declarative/decoders/test_json_decoder.py
  unit_tests/sources/declarative/extractors/test_dpath_extractor.py
Labels: chore

#334 fix(low code): Fix missing cursor for ClientSideIncrementalRecordFilterDecorator
  airbyte_cdk/sources/declarative/extractors/record_selector.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/extractors/test_record_selector.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
Labels: bug

#332 fix: (CDK) (Connector Builder) - refactor the `MessageGrouper` > `TestRead`
  airbyte_cdk/connector_builder/connector_builder_handler.py
  airbyte_cdk/connector_builder/message_grouper.py
  airbyte_cdk/connector_builder/test_reader/__init__.py
  airbyte_cdk/connector_builder/test_reader/helpers.py
  airbyte_cdk/connector_builder/test_reader/message_grouper.py
  airbyte_cdk/connector_builder/test_reader/reader.py
  airbyte_cdk/connector_builder/test_reader/types.py
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/connector_builder/test_message_grouper.py
  unit_tests/sources/declarative/decoders/test_decoders_memory_usage.py
  unit_tests/sources/declarative/decoders/test_json_decoder.py
Labels: bug, security, area/connector-builder, area/connector-builder/test-read

#260 feat(file-based): sync file acl permissions and identities
  airbyte_cdk/sources/file_based/config/abstract_file_based_spec.py
  airbyte_cdk/sources/file_based/config/validate_config_transfer_modes.py
  airbyte_cdk/sources/file_based/file_based_source.py
  airbyte_cdk/sources/file_based/file_based_stream_reader.py
  airbyte_cdk/sources/file_based/stream/__init__.py
  airbyte_cdk/sources/file_based/stream/identities_stream.py
  airbyte_cdk/sources/file_based/stream/permissions_file_based_stream.py
  airbyte_cdk/sources/specs/transfer_modes.py
  airbyte_cdk/sources/streams/permissions/identities_stream.py
  unit_tests/sources/file_based/in_memory_files_source.py
  unit_tests/sources/file_based/scenarios/csv_scenarios.py
  unit_tests/sources/file_based/stream/test_file_identities_stream.py
  unit_tests/sources/file_based/stream/test_permissions_file_based_stream.py
  unit_tests/sources/file_based/test_file_based_stream_reader.py
Labels: enhancement

#328 feat: check for request_option mapping conflicts in individual components
  airbyte_cdk/sources/declarative/incremental/datetime_based_cursor.py
  airbyte_cdk/sources/declarative/requesters/paginators/default_paginator.py
  airbyte_cdk/utils/mapping_helpers.py
  unit_tests/sources/declarative/requesters/paginators/test_default_paginator.py
  unit_tests/utils/test_mapping_helpers.py
Labels: enhancement

#342 feat(HttpMocker): adding support for PUT requests and bytes responses
  airbyte_cdk/test/mock_http/mocker.py
  airbyte_cdk/test/mock_http/response.py
  unit_tests/test/mock_http/test_mocker.py
Labels: enhancement

#331 feat(concurrent perpartition cursor): Refactor ConcurrentPerPartitionCursor
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
Labels: enhancement

#320 feat: Removes `stream_state` interpolation from CDK
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/interpolation/jinja.py
  airbyte_cdk/sources/declarative/requesters/http_requester.py
  airbyte_cdk/sources/declarative/requesters/request_options/interpolated_nested_request_input_provider.py
  airbyte_cdk/sources/declarative/requesters/request_options/interpolated_request_input_provider.py
  airbyte_cdk/sources/declarative/requesters/request_options/interpolated_request_options_provider.py
  airbyte_cdk/sources/declarative/retrievers/simple_retriever.py
  airbyte_cdk/sources/declarative/transformations/add_fields.py
  cdk-migrations.md
  unit_tests/sources/declarative/datetime/test_min_max_datetime.py
  unit_tests/sources/declarative/extractors/test_record_filter.py
  unit_tests/sources/declarative/extractors/test_record_selector.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
  unit_tests/sources/declarative/interpolation/test_jinja.py
  unit_tests/sources/declarative/partition_routers/test_parent_state_stream.py
  unit_tests/sources/declarative/requesters/request_options/test_interpolated_request_options_provider.py
  unit_tests/sources/declarative/requesters/test_interpolated_request_input_provider.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
  unit_tests/sources/declarative/test_concurrent_declarative_source.py
  unit_tests/sources/declarative/transformations/test_add_fields.py
Labels: enhancement

#348 fix: update CDK migration for 6.34.0
  cdk-migrations.md
Labels: bug, security

#351 feat: expose `str_to_datetime` jinja macro
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/interpolation/__init__.py
  airbyte_cdk/sources/declarative/interpolation/filters.py
  airbyte_cdk/sources/declarative/interpolation/interpolated_boolean.py
  airbyte_cdk/sources/declarative/interpolation/interpolated_mapping.py
  airbyte_cdk/sources/declarative/interpolation/interpolated_nested_mapping.py
  airbyte_cdk/sources/declarative/interpolation/interpolated_string.py
  airbyte_cdk/sources/declarative/interpolation/interpolation.py
  airbyte_cdk/sources/declarative/interpolation/jinja.py
  airbyte_cdk/sources/declarative/interpolation/macros.py
  unit_tests/sources/declarative/interpolation/test_macros.py
Labels: enhancement

#358 fix: (CDK) (CsvParser) - Fix the `\\` escaping when passing the `delimiter` from Builder's UI
  airbyte_cdk/sources/declarative/decoders/composite_raw_decoder.py
  unit_tests/sources/declarative/decoders/test_composite_decoder.py
Labels: bug, security

#347 feat(low-code cdk): add AbstractStreamFacade processing as concurrent streams in declarative source
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
Labels: enhancement

#353 feat(low-code cdk): add interpolation for limit field in Rate
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/requesters/test_http_requester.py
Labels: enhancement

#364 fix: update csv parser for builder compatibility
  airbyte_cdk/sources/declarative/decoders/composite_raw_decoder.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
Labels: bug, security

#343 feat(concurrent perpartition cursor): Add parent state updates
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
Labels: enhancement

#355 fix: (CDK) (ConnectorBuilder) - Add `auxiliary requests` to slice; support `TestRead` for AsyncRetriever (part 1/2)
  airbyte_cdk/connector_builder/models.py
  airbyte_cdk/connector_builder/test_reader/helpers.py
  airbyte_cdk/connector_builder/test_reader/message_grouper.py
  airbyte_cdk/connector_builder/test_reader/types.py
  airbyte_cdk/sources/declarative/auth/token_provider.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/http_logger.py
  airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/sources/test_http_logger.py
Labels: bug, security

#368 fix: (CDK) (AsyncRetriever) - Improve UX on variable naming and interpolation
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/requesters/README.md
  airbyte_cdk/sources/declarative/requesters/http_job_repository.py
  airbyte_cdk/sources/declarative/requesters/http_requester.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/requesters/test_http_job_repository.py
  unit_tests/sources/declarative/test_concurrent_declarative_source.py
Labels: bug, security, area/async-retriever

#369 feat: (low-code cdk) datetime format with milliseconds
  airbyte_cdk/sources/declarative/datetime/datetime_parser.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  unit_tests/sources/declarative/datetime/test_datetime_parser.py
Labels: enhancement
