Repository airbytehq/airbyte-python-cdk, pull requests merged in 2025-03, with the labels that each got.

#350 feat: improved custom components handling
  airbyte_cdk/sources/declarative/parsers/custom_code_compiler.py
Labels: enhancement

#382 chore: use python base image 4.0.0 in SDM
  Dockerfile
Labels: chore

#384 fix: Update DEFAULT_ERROR_MAPPING for InvalidURL to RETRY
  airbyte_cdk/sources/streams/http/error_handlers/default_error_mapping.py
  unit_tests/sources/streams/http/test_http.py
Labels: bug, security

#390 feat(low-code cdk): remove unnecessary manifest print
  airbyte_cdk/sources/declarative/yaml_declarative_source.py
Labels: enhancement

#388 feat: add formatting for epoch_microseconds
  airbyte_cdk/sources/declarative/datetime/__init__.py
  airbyte_cdk/sources/declarative/datetime/datetime_parser.py
  airbyte_cdk/sources/declarative/interpolation/macros.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/datetime/test_datetime_parser.py
  unit_tests/sources/declarative/extractors/test_record_filter.py
  unit_tests/sources/declarative/interpolation/test_macros.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
Labels: enhancement

#366 fix: prevent raw decoder from closing before sync completion
  airbyte_cdk/sources/declarative/decoders/composite_raw_decoder.py
  unit_tests/sources/declarative/decoders/test_composite_decoder.py
Labels: bug, security

#378 fix: (CDK) (AsyncRetriever) - Use the `Nested Decoders` to decode the streaming responses, instead of `ResponseToFileExtractor`
  airbyte_cdk/sources/declarative/decoders/composite_raw_decoder.py
  airbyte_cdk/sources/declarative/decoders/decoder.py
  airbyte_cdk/sources/declarative/decoders/decoder_parser.py
  airbyte_cdk/sources/declarative/decoders/zipfile_decoder.py
  airbyte_cdk/sources/declarative/extractors/response_to_file_extractor.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/requesters/http_requester.py
  unit_tests/sources/declarative/decoders/test_composite_decoder.py
  unit_tests/sources/declarative/decoders/test_zipfile_decoder.py
  unit_tests/sources/declarative/requesters/test_http_requester.py
Labels: bug, security

#392 fix(concurrent-cdk): StreamPartition handles AirbyteRecords
  airbyte_cdk/sources/streams/concurrent/adapters.py
  unit_tests/sources/streams/concurrent/test_adapters.py
Labels: bug

#371 feat(test): Allow mock server tests for manifest only sources
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/yaml_declarative_source.py
Labels: enhancement

#336 fix: fix PrintBuffer logic
  airbyte_cdk/entrypoint.py
  airbyte_cdk/logger.py
Labels: bug, security

#406 fix: (CDK) (DpathExtractor) - fix `schema` causing the `typescript type generation` in the FE
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
Labels: bug, security, declarative-component-schema, airbyte-python-cdk

#407 fix: (CDK) (manifest-only) - add ability to debug `manifest-only` sources / destinations
  debug_manifest/.gitignore
  debug_manifest/README.md
  debug_manifest/debug_manifest.py
  debug_manifest/resources/.gitkeep
Labels: bug, security

#402 feat(file-based): new AbstractFileBasedStreamPermissionsReader
  airbyte_cdk/sources/file_based/file_based_source.py
  airbyte_cdk/sources/file_based/file_based_stream_permissions_reader.py
  airbyte_cdk/sources/file_based/file_based_stream_reader.py
  airbyte_cdk/sources/file_based/stream/identities_stream.py
  airbyte_cdk/sources/file_based/stream/permissions_file_based_stream.py
  unit_tests/sources/file_based/stream/test_file_identities_stream.py
  unit_tests/sources/file_based/stream/test_permissions_file_based_stream.py
Labels: enhancement

#405 feat: Enable JobTracker limit configurability
  airbyte_cdk/sources/declarative/async_job/job_tracker.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/async_job/test_job_tracker.py
Labels: enhancement

#412 fix: (CDK) (HttpRequester) - fix `trailing slash` for `url_base` when no `path` has been provided
  airbyte_cdk/sources/declarative/requesters/http_requester.py
  unit_tests/sources/declarative/requesters/test_http_requester.py
Labels: bug, security, airbyte-python-cdk, airbyte-python-cdk/low-code/http-requester

#417 fix(file): Support column named type
  airbyte_cdk/sources/file_based/stream/default_file_based_stream.py
Labels: bug

#318 feat(low-code cdk): add StateDelegatingStream
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/retrievers/__init__.py
  unit_tests/sources/declarative/test_state_delegating_stream.py
Labels: enhancement

#419 fix: (CDK) (AsyncRetriever) - fix `availability strategy` issues, during `check connection`
  airbyte_cdk/sources/declarative/declarative_stream.py
  airbyte_cdk/sources/declarative/retrievers/async_retriever.py
Labels: bug, security, area/async-retriever, airbyte-python-cdk

#410 feat(low-code cdk): add overwrite flag to dpath flatten
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/transformations/add_fields.py
  airbyte_cdk/sources/declarative/transformations/dpath_flatten_fields.py
  unit_tests/sources/declarative/transformations/test_dpath_flatten_fields.py
Labels: enhancement

#411 fix(low-code cdk): fix set_initial_state for incremental_dependency and empty parent state
  airbyte_cdk/sources/declarative/partition_routers/substream_partition_router.py
Labels: bug

#421 fix(low-code cdk): fix partition router validation for async retriever
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
Labels: bug

#409 feat(low-code cdk): add condition to add fields
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/transformations/add_fields.py
  unit_tests/sources/declarative/transformations/test_add_fields.py
Labels: enhancement

#413 feat(low-code cdk): add transform_before_filtering to partition router schema
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
Labels: enhancement

#418 feat(low-code cdk): add lazy read to simple retriver
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/partition_routers/substream_partition_router.py
  airbyte_cdk/sources/declarative/requesters/paginators/strategies/cursor_pagination_strategy.py
  airbyte_cdk/sources/declarative/retrievers/__init__.py
  airbyte_cdk/sources/declarative/retrievers/simple_retriever.py
  unit_tests/sources/declarative/retrievers/test_lazy_simple_retriever.py
Labels: enhancement

#423 fix: exception oauth string error
  airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
Labels: bug, security

#425 fix: When grouping streams, ensure stream is declarative before checking in the manifest
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
Labels: bug, security

#424 feat: add `base64binascii_decode` to Jinja interpolation
  airbyte_cdk/sources/declarative/interpolation/filters.py
Labels: enhancement

#415 chore: rename AIRBYTE_ALLOW_CUSTOM_CODE to AIRBYTE_ENABLE_UNSAFE_CODE
  airbyte_cdk/sources/declarative/parsers/custom_code_compiler.py
Labels: chore

#428 fix: (CDK) (AsyncRetriever) - Add `polling_timeout` optional field
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/requesters/http_job_repository.py
  airbyte_cdk/sources/declarative/retrievers/async_retriever.py
Labels: bug, security, area/async-retriever, airbyte-python-cdk

#430 fix(test): Check method when comparing matchers
  airbyte_cdk/test/mock_http/mocker.py
  unit_tests/test/mock_http/test_mocker.py
Labels: bug

#435 feat: enable async job configurability via `config`
  airbyte_cdk/sources/declarative/async_job/job_tracker.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  unit_tests/sources/declarative/async_job/test_job_tracker.py
Labels: enhancement

#434 fix: update decoder title & descriptions for improved tooltip
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
Labels: bug, security

#354 feat(low code): Add GroupingPartitionRouter
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/partition_routers/__init__.py
  airbyte_cdk/sources/declarative/partition_routers/grouping_partition_router.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/partition_routers/test_grouping_partition_router.py
Labels: enhancement

#436 fix: ensure most_recent_cursor_value is deserialized
  airbyte_cdk/sources/streams/concurrent/state_converters/abstract_stream_state_converter.py
  unit_tests/sources/streams/concurrent/test_cursor.py
Labels: bug, security

#444 fix: substreampartitionrouter state migration from child when it is empty
  airbyte_cdk/sources/declarative/partition_routers/substream_partition_router.py
  unit_tests/sources/declarative/partition_routers/test_substream_partition_router.py
Labels: bug, security

#440 chore(low-code cdk): add pagination to http resolver unit tests
  unit_tests/sources/declarative/resolvers/test_http_components_resolver.py
Labels: chore

#442 feat(connector-builder): add full_resolve command to connector builder
  airbyte_cdk/connector_builder/connector_builder_handler.py
  airbyte_cdk/connector_builder/main.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/sources/declarative/resolvers/test_http_components_resolver.py
Labels: enhancement

#448 feat(low code cdk): updated format_datetime macros to format timestamps
  airbyte_cdk/sources/declarative/interpolation/macros.py
  unit_tests/sources/declarative/interpolation/test_macros.py
Labels: enhancement

#449 feat(file-mode-api): move file uploader to record selector level.
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/extractors/record_selector.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/retrievers/file_uploader.py
  airbyte_cdk/sources/declarative/stream_slicers/declarative_partition_generator.py
Labels: enhancement

#453 feat(file-mode-api: add filename extractor component
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/retrievers/file_uploader.py
  unit_tests/sources/declarative/file/test_file_stream.py
  unit_tests/sources/declarative/file/test_file_stream_with_filename_extractor.yaml
Labels: enhancement
