Repository airbytehq/airbyte-python-cdk, pull requests merged in 2025-05, with the labels that each got.

#525 chore: fix more fields in declarative_component_schema
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
Labels: chore

#532 fix: parametrize the connector name in the template code documentation
  airbyte_cdk/cli/airbyte_cdk/_connector.py
Labels: bug, security

#535 fix: (CDK) (BaseModelWithDeprecations) - filter the warnings to be shown, ignore the `SyntaxWarning`
  airbyte_cdk/sources/declarative/models/base_model_with_deprecations.py
Labels: bug, security, airbyte-python-cdk

#531 tests: handle case of `acceptance-test-config.yml` with no valid test cases
  airbyte_cdk/test/entrypoint_wrapper.py
  airbyte_cdk/test/standard_tests/_job_runner.py
  airbyte_cdk/test/standard_tests/connector_base.py
  airbyte_cdk/test/standard_tests/declarative_sources.py
  airbyte_cdk/test/standard_tests/models/scenario.py
  airbyte_cdk/test/standard_tests/source_base.py
Labels: testing

#536 feat(low-code cdk): Allow for multiple schema_loaders to be defined for a stream
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/schema/composite_schema_loader.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/schema/test_composite_schema_loader.py
Labels: enhancement

#539 fix(cdk): fix state emit for ConcurrentPerPartitionCursor
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
Labels: bug

#541 feat(AsyncRetriever): slice information during the polling request, Support creation_response interpolation in body
  airbyte_cdk/sources/declarative/requesters/http_job_repository.py
  airbyte_cdk/sources/declarative/requesters/request_options/interpolated_nested_request_input_provider.py
  airbyte_cdk/sources/declarative/requesters/request_options/interpolated_request_input_provider.py
  unit_tests/sources/declarative/requesters/test_http_job_repository.py
Labels: enhancement

#534 fix(connector-builder): fix dynamic stream read with dynamic schema
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/retrievers/simple_retriever.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
Labels: bug

#533 feat: implement validators, validation strategies, and RemapField transformer
  airbyte_cdk/sources/declarative/transformations/config_transformations/__init__.py
  airbyte_cdk/sources/declarative/transformations/config_transformations/add_fields.py
  airbyte_cdk/sources/declarative/transformations/config_transformations/config_transformation.py
  airbyte_cdk/sources/declarative/transformations/config_transformations/remap_field.py
  airbyte_cdk/sources/declarative/transformations/config_transformations/remove_fields.py
  airbyte_cdk/sources/declarative/validators/__init__.py
  airbyte_cdk/sources/declarative/validators/dpath_validator.py
  airbyte_cdk/sources/declarative/validators/predicate_validator.py
  airbyte_cdk/sources/declarative/validators/validate_adheres_to_schema.py
  airbyte_cdk/sources/declarative/validators/validation_strategy.py
  airbyte_cdk/sources/declarative/validators/validator.py
  unit_tests/sources/declarative/transformations/config_transformations/test_config_add_fields.py
  unit_tests/sources/declarative/transformations/config_transformations/test_config_remap_field.py
  unit_tests/sources/declarative/transformations/config_transformations/test_config_remove_fields.py
  unit_tests/sources/declarative/validators/test_dpath_validator.py
  unit_tests/sources/declarative/validators/test_predicate_validator.py
  unit_tests/sources/declarative/validators/test_validate_adheres_to_schema.py
Labels: enhancement

#542 fix(concurrent perpartition cursor): Increase throttle time to 10 minutes
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
Labels: bug

#543 feat(low-code): pass top level params to PropertiesFromEndpoint requester
  airbyte_cdk/sources/declarative/parsers/manifest_component_transformer.py
  unit_tests/sources/declarative/parsers/test_manifest_component_transformer.py
Labels: enhancement

#544 fix(cdk): determine state from manager if not received a state in per partition router
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/parsers/resources/stream_with_incremental_and_aync_retriever_with_partition_router.yaml
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
Labels: bug

#546 fix(cdk): pass transformations to concurrent cursor and fix transformation
  airbyte_cdk/sources/declarative/migrations/legacy_to_per_partition_state_migration.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/migrations/test_legacy_to_per_partition_migration.py
  unit_tests/sources/declarative/parsers/resources/stream_with_incremental_and_aync_retriever_with_partition_router.yaml
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
Labels: bug

#547 fix: fixes pre-commit-config and adds type-checking; updates poe tasks
  .pre-commit-config.yaml
  pyproject.toml
Labels: bug, security, airbyte-python-cdk

#545 feat(cli): accept dynamic GCP project ID from env var during secrets fetch
  airbyte_cdk/cli/airbyte_cdk/_secrets.py
Labels: enhancement

#557 fix: remove unit_tests directory from coverage report and add handling of tmp files
  .coveragerc
Labels: bug, security

#556 feat(sdm-cli): add new args --manifest-path and --components-path to SDM CLI
  airbyte_cdk/cli/source_declarative_manifest/_run.py
  airbyte_cdk/connector.py
  airbyte_cdk/entrypoint.py
  unit_tests/source_declarative_manifest/conftest.py
  unit_tests/source_declarative_manifest/test_source_declarative_remote_manifest.py
  unit_tests/source_declarative_manifest/test_source_declarative_w_custom_components.py
  unit_tests/test_entrypoint.py
Labels: enhancement

#538 feat: extend spec class for config migrations
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/spec/__init__.py
  airbyte_cdk/sources/declarative/spec/spec.py
  airbyte_cdk/sources/declarative/transformations/config_transformations/add_fields.py
  airbyte_cdk/sources/declarative/transformations/config_transformations/remap_field.py
  airbyte_cdk/sources/declarative/validators/dpath_validator.py
  poetry.lock
  unit_tests/sources/declarative/spec/test_spec.py
  unit_tests/sources/declarative/transformations/config_transformations/test_config_add_fields.py
Labels: enhancement

#550 feat(cdk): add schema filter to DynamicSchemaLoader
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/schema/dynamic_schema_loader.py
  unit_tests/sources/declarative/schema/test_dynamic_schema_loader.py
Labels: enhancement

#561 feat: update `ManifestDeclarativeSource` to invoke declarative config migrations/transformations/validations
  airbyte_cdk/cli/source_declarative_manifest/_run.py
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/spec/spec.py
  airbyte_cdk/sources/declarative/yaml_declarative_source.py
  unit_tests/sources/declarative/spec/test_spec.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
Labels: enhancement

#563 feat: adds config_path to source instantiation for sdm, enabling config migrations
  airbyte_cdk/cli/source_declarative_manifest/_run.py
Labels: enhancement

#565 fix: update `pytest-fast` poe command to specify `unit_tests/` directory, enabling `--skipslow` option usage
  pyproject.toml
Labels: bug, security
