Repository airbytehq/airbyte-python-cdk, pull requests merged in 2025-06, with the labels that each got.

#572 feat(cdk): more unit test for jinja interpolation
  unit_tests/sources/declarative/interpolation/test_interpolated_string.py
Labels: enhancement

#567 fix(connector-builder): fix property chunking in connector builder
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/retrievers/__init__.py
  airbyte_cdk/sources/declarative/retrievers/simple_retriever.py
  airbyte_cdk/sources/declarative/stream_slicers/__init__.py
  airbyte_cdk/sources/declarative/stream_slicers/stream_slicer_test_read_decorator.py
  airbyte_cdk/sources/streams/concurrent/partitions/stream_slicer.py
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/connector_builder/test_property_chunking.py
  unit_tests/resource/http/response/declarative/property_chunking/rates_one_two.json
  unit_tests/resource/http/response/declarative/property_chunking/rates_three_four.json
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
  unit_tests/sources/declarative/stream_slicers/test_stream_slicer_read_decorator.py
Labels: bug

#575 feat(cdk): add option to make empty cells None when parsing csv with CsvParser
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/decoders/composite_raw_decoder.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/decoders/test_composite_decoder.py
Labels: enhancement

#590 feat: update `DpathValidator` to skip validation if returned value is falsy
  airbyte_cdk/sources/declarative/validators/dpath_validator.py
  unit_tests/sources/declarative/validators/test_dpath_validator.py
Labels: enhancement

#568 fix(concurrent-perpartition-cursor): Fix memory issues
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
Labels: bug

#586 tests: add docker-based tests to FAST standard tests
  .github/workflows/connector-tests.yml
  airbyte_cdk/cli/airbyte_cdk/_connector.py
  airbyte_cdk/cli/airbyte_cdk/_image.py
  airbyte_cdk/cli/airbyte_cdk/_secrets.py
  airbyte_cdk/models/airbyte_protocol_serializers.py
  airbyte_cdk/models/connector_metadata.py
  airbyte_cdk/test/entrypoint_wrapper.py
  airbyte_cdk/test/models/scenario.py
  airbyte_cdk/test/standard_tests/__init__.py
  airbyte_cdk/test/standard_tests/connector_base.py
  airbyte_cdk/test/standard_tests/docker_base.py
  airbyte_cdk/test/standard_tests/pytest_hooks.py
  airbyte_cdk/test/standard_tests/source_base.py
  airbyte_cdk/test/standard_tests/util.py
  airbyte_cdk/utils/connector_paths.py
  airbyte_cdk/utils/docker.py
  poetry.lock
  pyproject.toml
  unit_tests/resources/source_pokeapi_w_components_py/metadata.yaml
Labels: testing

#603 fix: resolve issue in connector dir discovery
  airbyte_cdk/utils/connector_paths.py
Labels: bug, security

#606 fix(tests): resolve issue with 'exception' status raising failure of FAST container tests
  airbyte_cdk/test/models/outcome.py
Labels: bug

#605 fix(low-code): sync records without cursor field in ConcurrentPerPartitionCursor
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
  unit_tests/sources/declarative/resolvers/test_parametrized_components_resolver.py
Labels: bug

#608 fix: config remap fields component to provide correct config context
  airbyte_cdk/sources/declarative/transformations/config_transformations/remap_field.py
Labels: bug, security

#610 feat: enable custom validation strategies
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
Labels: enhancement

#599 fix: manifest normalization
  airbyte_cdk/sources/declarative/parsers/manifest_normalizer.py
  unit_tests/sources/declarative/parsers/conftest.py
  unit_tests/sources/declarative/parsers/resources/abnormal_schemas_manifest.yaml
  unit_tests/sources/declarative/parsers/test_manifest_normalizer.py
Labels: bug, security

#618 tests: add debug option for entrypoint wrapper
  airbyte_cdk/test/entrypoint_wrapper.py
Labels: testing

#621 docs: integrate the SDM readme into `pdoc` (targets #620)
  airbyte_cdk/__init__.py
  airbyte_cdk/cli/source_declarative_manifest/__init__.py
  airbyte_cdk/cli/source_declarative_manifest/_run.py
Labels: docs

#620 docs: add Readme for sdm commands
  airbyte_cdk/__init__.py
  airbyte_cdk/cli/source_declarative_manifest/README.md
  airbyte_cdk/cli/source_declarative_manifest/__init__.py
  airbyte_cdk/cli/source_declarative_manifest/_run.py
Labels: docs
