Repository airbytehq/airbyte-python-cdk, pull requests merged in 2025-04, with the labels that each got.

#454 feat(low code cdk): add path to filter interpolation in AddFields condition
  airbyte_cdk/sources/declarative/transformations/add_fields.py
  unit_tests/sources/declarative/transformations/test_add_fields.py
Labels: enhancement

#455 feat(low-code cdk): add streams limit to full resolve manifest command
  airbyte_cdk/connector_builder/connector_builder_handler.py
  airbyte_cdk/connector_builder/main.py
  unit_tests/connector_builder/test_connector_builder_handler.py
Labels: enhancement

#452 feat(Low-Code CDK Property Chunking): Allow fetching query properties and property chunking for low-code sources
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/requesters/query_properties/__init__.py
  airbyte_cdk/sources/declarative/requesters/query_properties/properties_from_endpoint.py
  airbyte_cdk/sources/declarative/requesters/query_properties/property_chunking.py
  airbyte_cdk/sources/declarative/requesters/query_properties/query_properties.py
  airbyte_cdk/sources/declarative/requesters/query_properties/strategies/__init__.py
  airbyte_cdk/sources/declarative/requesters/query_properties/strategies/group_by_key.py
  airbyte_cdk/sources/declarative/requesters/query_properties/strategies/merge_strategy.py
  airbyte_cdk/sources/declarative/requesters/request_options/interpolated_request_options_provider.py
  airbyte_cdk/sources/declarative/retrievers/simple_retriever.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/requesters/query_properties/__init__.py
  unit_tests/sources/declarative/requesters/query_properties/test_group_by_key.py
  unit_tests/sources/declarative/requesters/query_properties/test_properties_from_endpoint.py
  unit_tests/sources/declarative/requesters/query_properties/test_property_chunking.py
  unit_tests/sources/declarative/requesters/query_properties/test_query_properties.py
  unit_tests/sources/declarative/requesters/request_options/test_interpolated_request_options_provider.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
  unit_tests/sources/declarative/schema/test_dynamic_schema_loader.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
Labels: enhancement

#459 fix: locally running tests errors
  airbyte_cdk/sources/declarative/interpolation/macros.py
  airbyte_cdk/sources/declarative/schema/default_schema_loader.py
  unit_tests/sources/declarative/interpolation/test_macros.py
Labels: bug, security

#469 CI: Implement automatic dynamic versioning for pre-releases
  .github/workflows/pypi_publish.yml
  docs/RELEASES.md
  pyproject.toml
Labels: ci

#471 ci(hotfix): update version detection format in workflow
  .github/workflows/pypi_publish.yml
  pyproject.toml
Labels: ci

#473 chore: auto-format YAML and Markdown files
  .github/workflows/connector-tests.yml
  .github/workflows/docker-build-check.yml
  .github/workflows/pypi_publish.yml
  .github/workflows/python_dependency_analysis.yml
  .github/workflows/semantic_pr_check.yml
  .github/workflows/slash_command_dispatch.yml
  debug_manifest/README.md
  docs/CONTRIBUTING.md
  pyproject.toml
Labels: chore

#482 fix: Ensure page token 0 is being passed
  airbyte_cdk/sources/declarative/retrievers/simple_retriever.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
Labels: bug, security

#472 feat(low-code): added key_transformation to DpathFlattenFields
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/transformations/dpath_flatten_fields.py
  unit_tests/sources/declarative/transformations/test_dpath_flatten_fields.py
Labels: enhancement

#484 fix(OffsetIncrement Pagination Strategy): Fix bug where streams that use record filtering do not paginate correctly
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/requesters/paginators/strategies/offset_increment.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/requesters/paginators/test_default_paginator.py
  unit_tests/sources/declarative/requesters/paginators/test_offset_increment.py
Labels: bug

#462 fix: no longer require token expiration from the OAuth resource server
  airbyte_cdk/sources/declarative/auth/oauth.py
  airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
  airbyte_cdk/sources/streams/http/requests_native_auth/oauth.py
  unit_tests/sources/declarative/auth/test_oauth.py
  unit_tests/sources/streams/http/requests_native_auth/test_requests_native_auth.py
Labels: bug, security

#490 fix: Properly setup global substream cursor based on manifest
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
Labels: bug, security

#487 fix(property chunking): Switch the ordering page iteration and property chunking process chunks first instead of pages first
  airbyte_cdk/sources/declarative/requesters/query_properties/property_chunking.py
  airbyte_cdk/sources/declarative/retrievers/simple_retriever.py
  unit_tests/sources/declarative/requesters/query_properties/test_property_chunking.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
Labels: bug

#495 fix(property chunking): fix delimiter count since commas are encoded as three characters
  airbyte_cdk/sources/declarative/requesters/query_properties/property_chunking.py
  unit_tests/sources/declarative/requesters/query_properties/test_property_chunking.py
Labels: bug

#498 tests: re-enable file-based connector (google-drive) in CDK downstream connector tests
  .github/workflows/connector-tests.yml
Labels: testing

#433 feat(file-api): new upload component for declarative cdk and update protocol support for file-based connectors
  airbyte_cdk/models/__init__.py
  airbyte_cdk/models/airbyte_protocol.py
  airbyte_cdk/models/file_transfer_record_message.py
  airbyte_cdk/sources/concurrent_source/concurrent_read_processor.py
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/extractors/record_selector.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/retrievers/file_uploader.py
  airbyte_cdk/sources/declarative/stream_slicers/declarative_partition_generator.py
  airbyte_cdk/sources/file_based/file_based_stream_reader.py
  airbyte_cdk/sources/file_based/file_record_data.py
  airbyte_cdk/sources/file_based/file_types/file_transfer.py
  airbyte_cdk/sources/file_based/schema_helpers.py
  airbyte_cdk/sources/file_based/stream/concurrent/adapters.py
  airbyte_cdk/sources/file_based/stream/default_file_based_stream.py
  airbyte_cdk/sources/file_based/stream/permissions_file_based_stream.py
  airbyte_cdk/sources/streams/concurrent/default_stream.py
  airbyte_cdk/sources/types.py
  airbyte_cdk/sources/utils/files_directory.py
  airbyte_cdk/sources/utils/record_helper.py
  airbyte_cdk/test/mock_http/response_builder.py
  poetry.lock
  pyproject.toml
  unit_tests/resource/http/response/file_api/article_attachment_content.png
  unit_tests/resource/http/response/file_api/article_attachments.json
  unit_tests/resource/http/response/file_api/articles.json
  unit_tests/sources/declarative/file/__init__.py
  unit_tests/sources/declarative/file/file_stream_manifest.yaml
  unit_tests/sources/declarative/file/test_file_stream.py
  unit_tests/sources/declarative/file/test_file_stream_with_filename_extractor.yaml
  unit_tests/sources/file_based/in_memory_files_source.py
  unit_tests/sources/file_based/scenarios/csv_scenarios.py
  unit_tests/sources/file_based/scenarios/incremental_scenarios.py
  unit_tests/sources/file_based/stream/test_default_file_based_stream.py
  unit_tests/sources/file_based/test_file_based_stream_reader.py
  unit_tests/sources/streams/concurrent/scenarios/stream_facade_scenarios.py
  unit_tests/sources/streams/concurrent/scenarios/thread_based_concurrent_stream_scenarios.py
  unit_tests/sources/streams/concurrent/test_concurrent_read_processor.py
  unit_tests/sources/streams/concurrent/test_default_stream.py
Labels: enhancement

#501 fix: only check for file upload if stream is declarative
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
Labels: bug, security

#496 feat: remove 1-or-more stream validation
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
Labels: enhancement

#505 ci: add `/poe` slash command for CDK PRs and Issues
  .github/workflows/poe-command.yml
  .github/workflows/slash_command_dispatch.yml
Labels: ci

#493 feat: add `airbyte-cdk` CLI with support for: `connector test`, `secrets fetch` and `--version`
  .gitignore
  airbyte_cdk/cli/airbyte_cdk/__init__.py
  airbyte_cdk/cli/airbyte_cdk/_connector.py
  airbyte_cdk/cli/airbyte_cdk/_image.py
  airbyte_cdk/cli/airbyte_cdk/_manifest.py
  airbyte_cdk/cli/airbyte_cdk/_secrets.py
  airbyte_cdk/cli/airbyte_cdk/_util.py
  airbyte_cdk/cli/airbyte_cdk/_version.py
  airbyte_cdk/test/standard_tests/connector_base.py
  airbyte_cdk/test/standard_tests/declarative_sources.py
  airbyte_cdk/test/standard_tests/test_resources.py
  airbyte_cdk/test/standard_tests/util.py
  docs/CONTRIBUTING.md
  poetry.lock
  pyproject.toml
  unit_tests/source_declarative_manifest/test_source_declarative_w_custom_components.py
Labels: enhancement

#480 fix: (CDK) (design) correct field titles/orders in `declarative_component_schema.yaml`
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
Labels: bug, security

#447 fix: (CDK) (Manifest) - Add `Manifest Normalization` module (reduce commonalities + handle schema $refs)
  airbyte_cdk/connector_builder/connector_builder_handler.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/custom_exceptions.py
  airbyte_cdk/sources/declarative/parsers/manifest_component_transformer.py
  airbyte_cdk/sources/declarative/parsers/manifest_normalizer.py
  airbyte_cdk/sources/declarative/parsers/manifest_reference_resolver.py
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/sources/declarative/parsers/conftest.py
  unit_tests/sources/declarative/parsers/resources/abnormal_schemas_manifest.yaml
  unit_tests/sources/declarative/parsers/test_manifest_normalizer.py
  unit_tests/sources/declarative/parsers/test_manifest_reference_resolver.py
Labels: bug, security, declarative-component-schema, airbyte-python-cdk

#504 feat: new CLI: `airbyte-cdk image build`
  airbyte_cdk/cli/__init__.py
  airbyte_cdk/cli/airbyte_cdk/_image.py
  airbyte_cdk/models/connector_metadata.py
  airbyte_cdk/utils/docker.py
  airbyte_cdk/utils/docker_image_templates.py
Labels: enhancement

#508 fix: yield partitions for unique stream slices in StreamSlicerPartitionGenerator
  airbyte_cdk/sources/declarative/stream_slicers/declarative_partition_generator.py
Labels: bug, security

#510 chore: revert generate unique partitions added in #508
  airbyte_cdk/sources/declarative/stream_slicers/declarative_partition_generator.py
Labels: chore

#513 fix(low-code cdk): pass state_migrations when creating concurrent cursor in _group_streams
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
Labels: bug

#503 feat(cdk): connector builder support for file uploader
  airbyte_cdk/sources/declarative/extractors/record_selector.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/retrievers/file_uploader/__init__.py
  airbyte_cdk/sources/declarative/retrievers/file_uploader/connector_builder_file_uploader.py
  airbyte_cdk/sources/declarative/retrievers/file_uploader/default_file_uploader.py
  airbyte_cdk/sources/declarative/retrievers/file_uploader/file_uploader.py
  airbyte_cdk/sources/declarative/retrievers/file_uploader/file_writer.py
  airbyte_cdk/sources/declarative/retrievers/file_uploader/local_file_system_file_writer.py
  airbyte_cdk/sources/declarative/retrievers/file_uploader/noop_file_writer.py
  unit_tests/sources/declarative/file/test_file_stream.py
Labels: enhancement

#485 fix: (CDK) (Declarative) - Add `Manifest Migration` module
  airbyte_cdk/connector_builder/connector_builder_handler.py
  airbyte_cdk/manifest_migrations/README.md
  airbyte_cdk/manifest_migrations/__init__.py
  airbyte_cdk/manifest_migrations/exceptions.py
  airbyte_cdk/manifest_migrations/manifest_migration.py
  airbyte_cdk/manifest_migrations/migration_handler.py
  airbyte_cdk/manifest_migrations/migrations/__init__.py
  airbyte_cdk/manifest_migrations/migrations/http_requester_path_to_url.py
  airbyte_cdk/manifest_migrations/migrations/http_requester_request_body_json_data_to_request_body.py
  airbyte_cdk/manifest_migrations/migrations/http_requester_url_base_to_url.py
  airbyte_cdk/manifest_migrations/migrations/registry.yaml
  airbyte_cdk/manifest_migrations/migrations_registry.py
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  unit_tests/manifest_migrations/conftest.py
  unit_tests/manifest_migrations/test_manifest_migration.py
Labels: bug, security, airbyte-python-cdk/low-code, manifest, migrations

#515 fix(low-code): set transform_before_filtering from manifest if client_side_incremental_sync=true
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/test_concurrent_declarative_source.py
Labels: bug

#486 fix: (CDK) (Manifest) - Add `deprecations` support and handle `deprecation warnings`; deprecate `url_base`, `path`, `request_body_json` and `request_body_data` for `HttpRequester`
  airbyte_cdk/connector_builder/test_reader/reader.py
  airbyte_cdk/manifest_migrations/migrations/registry.yaml
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/declarative_source.py
  airbyte_cdk/sources/declarative/interpolation/interpolated_nested_mapping.py
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/models/base_model_with_deprecations.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/requesters/http_requester.py
  airbyte_cdk/sources/declarative/requesters/request_options/interpolated_request_options_provider.py
  airbyte_cdk/sources/declarative/requesters/requester.py
  bin/generate_component_manifest_files.py
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/manifest_migrations/conftest.py
  unit_tests/sources/declarative/requesters/request_options/test_interpolated_request_options_provider.py
Labels: bug, security

#518 fix: (CDK) (Manifest Migration) - correct the migration versions to `v6.48.2`
  airbyte_cdk/manifest_migrations/migrations/registry.yaml
  unit_tests/manifest_migrations/conftest.py
Labels: bug, security, airbyte-python-cdk, migrations

#521 fix: (CDK) (Manifest Migration) - fix the `request_body_json / request_body_data` > `request_body` migration
  airbyte_cdk/manifest_migrations/migrations/http_requester_request_body_json_data_to_request_body.py
  airbyte_cdk/manifest_migrations/migrations/registry.yaml
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/requesters/request_options/interpolated_request_options_provider.py
  unit_tests/manifest_migrations/conftest.py
  unit_tests/sources/declarative/requesters/request_options/test_interpolated_request_options_provider.py
Labels: bug, security, airbyte-python-cdk, manifest, migrations

#520 feat(cli): add `secrets list` CLI command and github ci secrets masking
  airbyte_cdk/cli/airbyte_cdk/_secrets.py
  airbyte_cdk/cli/airbyte_cdk/_util.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#519 feat(cdk): allow empty secrets (bing-ads)
  airbyte_cdk/sources/declarative/auth/oauth.py
  unit_tests/sources/declarative/auth/test_oauth.py
Labels: enhancement

#522 feat(cli): add support for building images for java connectors
  airbyte_cdk/utils/docker.py
  airbyte_cdk/utils/docker_image_templates.py
Labels: enhancement
