Repository airbytehq/airbyte-python-cdk, pull requests merged in 2025-09, with the labels that each got.

#707 chore: remove declarative stream
  airbyte_cdk/legacy/sources/declarative/incremental/per_partition_cursor.py
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  airbyte_cdk/sources/declarative/incremental/global_substream_cursor.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/partition_routers/cartesian_product_stream_slicer.py
  airbyte_cdk/sources/declarative/partition_routers/grouping_partition_router.py
  airbyte_cdk/sources/declarative/partition_routers/list_partition_router.py
  airbyte_cdk/sources/declarative/partition_routers/partition_router.py
  airbyte_cdk/sources/declarative/partition_routers/single_partition_router.py
  airbyte_cdk/sources/declarative/partition_routers/substream_partition_router.py
  airbyte_cdk/sources/declarative/requesters/request_options/per_partition_request_option_provider.py
  airbyte_cdk/sources/declarative/resolvers/http_components_resolver.py
  airbyte_cdk/sources/declarative/retrievers/retriever.py
  airbyte_cdk/sources/message/repository.py
  cdk-migrations.md
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/legacy/sources/declarative/incremental/test_per_partition_cursor.py
  unit_tests/legacy/sources/declarative/partition_routers/__init__.py
  unit_tests/legacy/sources/declarative/partition_routers/test_parent_state_stream.py
  unit_tests/legacy/sources/declarative/test_manifest_declarative_source.py
  unit_tests/sources/declarative/file/file_stream_manifest.yaml
  unit_tests/sources/declarative/file/test_file_stream_with_filename_extractor.yaml
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
  unit_tests/sources/declarative/incremental/test_per_partition_cursor_integration.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/parsers/testing_components.py
  unit_tests/sources/declarative/partition_routers/helpers.py
  unit_tests/sources/declarative/partition_routers/test_cartesian_product_partition_router.py
  unit_tests/sources/declarative/partition_routers/test_grouping_partition_router.py
  unit_tests/sources/declarative/partition_routers/test_substream_partition_router.py
  unit_tests/sources/declarative/requesters/request_options/test_per_partition_request_option_provider.py
  unit_tests/sources/declarative/resolvers/test_http_components_resolver.py
  unit_tests/sources/declarative/test_concurrent_declarative_source.py
  unit_tests/sources/streams/concurrent/scenarios/thread_based_concurrent_stream_source_builder.py
Labels: chore

#744 feat: add trace tags for manifest-server
  airbyte_cdk/manifest_server/api_models/__init__.py
  airbyte_cdk/manifest_server/api_models/manifest.py
  airbyte_cdk/manifest_server/helpers/__init__.py
  airbyte_cdk/manifest_server/helpers/auth.py
  airbyte_cdk/manifest_server/helpers/tracing.py
  airbyte_cdk/manifest_server/routers/manifest.py
  unit_tests/manifest_server/helpers/__init__.py
  unit_tests/manifest_server/helpers/test_auth.py
Labels: enhancement

#745 fix(manifest-server): descriptor can be dict
  airbyte_cdk/manifest_server/api_models/stream.py
Labels: bug

#750 chore: regenerate manifest-server openapi spec
  airbyte_cdk/manifest_server/openapi.yaml
Labels: chore

#763 fix: update deprecated jsonschema import to use protocols module
  airbyte_cdk/sources/utils/transform.py
Labels: bug, security

#741 chore: exclude auto-generated OpenAPI file and GitHub workflows from YAML formatting
  .prettierignore
Labels: chore

#770 feat: support state migrations that affects parent streams
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/parsers/testing_components.py
Labels: enhancement

#774 fix: properly handle multi-line secrets in secret masking
  airbyte_cdk/cli/airbyte_cdk/_secrets.py
  unit_tests/cli/airbyte_cdk/test_secret_masks.py
Labels: bug, security

#777 fix: noproxy that breaks regression tests
  airbyte_cdk/sources/streams/http/http_client.py
  unit_tests/sources/streams/http/test_http_client.py
Labels: bug, security
