Repository airbytehq/airbyte-python-cdk, pull requests merged in 2025-08, with the labels that each got.

#687 fix: make incremental_sync not linkable
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
Labels: bug, security

#690 fix: state migration
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
Labels: bug, security

#692 fix: properly join url and path when calculating full url
  airbyte_cdk/sources/declarative/requesters/http_requester.py
  unit_tests/sources/declarative/requesters/test_http_requester.py
Labels: bug, security

#695 fix: url and path joining for cursor paginators
  airbyte_cdk/sources/declarative/requesters/http_requester.py
  airbyte_cdk/sources/declarative/requesters/paginators/default_paginator.py
  unit_tests/sources/declarative/requesters/paginators/test_default_paginator.py
Labels: bug, security

#682 docs: Document `/poe build` slash command.
  .github/pr-welcome-internal.md
  docs/CONTRIBUTING.md
Labels: docs

#698 feat: Add --no-creds option to connector and image test commands
  airbyte_cdk/cli/airbyte_cdk/_connector.py
  airbyte_cdk/cli/airbyte_cdk/_image.py
  airbyte_cdk/test/models/scenario.py
  airbyte_cdk/test/standard_tests/pytest_hooks.py
Labels: enhancement

#686 chore: have declarative availability check support AbstractStream
  airbyte_cdk/sources/declarative/checks/check_dynamic_stream.py
  airbyte_cdk/sources/declarative/checks/check_stream.py
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/file_based/availability_strategy/__init__.py
  airbyte_cdk/sources/file_based/availability_strategy/abstract_file_based_availability_strategy.py
  airbyte_cdk/sources/file_based/stream/abstract_file_based_stream.py
  airbyte_cdk/sources/file_based/stream/concurrent/adapters.py
  airbyte_cdk/sources/streams/availability_strategy.py
  airbyte_cdk/sources/streams/concurrent/abstract_stream.py
  airbyte_cdk/sources/streams/concurrent/adapters.py
  airbyte_cdk/sources/streams/concurrent/availability_strategy.py
  airbyte_cdk/sources/streams/concurrent/default_stream.py
  unit_tests/sources/declarative/checks/test_check_stream.py
  unit_tests/sources/streams/concurrent/scenarios/thread_based_concurrent_stream_scenarios.py
  unit_tests/sources/streams/concurrent/test_adapters.py
  unit_tests/sources/streams/concurrent/test_default_stream.py
Labels: chore

#701 docs: adjust descriptions of page token option
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
Labels: docs

#699 fix(connector-builder): remerge concurrent cdk builder changes
  airbyte_cdk/connector_builder/connector_builder_handler.py
  airbyte_cdk/connector_builder/main.py
  airbyte_cdk/connector_builder/test_reader/helpers.py
  airbyte_cdk/connector_builder/test_reader/message_grouper.py
  airbyte_cdk/sources/concurrent_source/concurrent_read_processor.py
  airbyte_cdk/sources/concurrent_source/concurrent_source.py
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/stream_slicers/declarative_partition_generator.py
  airbyte_cdk/sources/declarative/stream_slicers/stream_slicer_test_read_decorator.py
  airbyte_cdk/sources/message/concurrent_repository.py
  airbyte_cdk/sources/streams/concurrent/partition_reader.py
  airbyte_cdk/sources/streams/concurrent/partitions/types.py
  airbyte_cdk/sources/utils/slice_logger.py
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/connector_builder/test_message_grouper.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
  unit_tests/sources/declarative/schema/test_dynamic_schema_loader.py
  unit_tests/sources/declarative/stream_slicers/test_declarative_partition_generator.py
  unit_tests/sources/streams/concurrent/scenarios/stream_facade_builder.py
  unit_tests/sources/streams/concurrent/test_concurrent_read_processor.py
  unit_tests/sources/streams/concurrent/test_partition_reader.py
Labels: bug

#716 fix: revert connector builder limitation wrongly applied to all the streams
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
Labels: bug, security

#712 fix(connector-builder): Re-revert "fix: revert remerge concurrent cdk builder change because of flaky test"
  airbyte_cdk/connector_builder/connector_builder_handler.py
  airbyte_cdk/connector_builder/main.py
  airbyte_cdk/connector_builder/test_reader/helpers.py
  airbyte_cdk/connector_builder/test_reader/message_grouper.py
  airbyte_cdk/sources/concurrent_source/concurrent_read_processor.py
  airbyte_cdk/sources/concurrent_source/concurrent_source.py
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/stream_slicers/declarative_partition_generator.py
  airbyte_cdk/sources/declarative/stream_slicers/stream_slicer_test_read_decorator.py
  airbyte_cdk/sources/message/concurrent_repository.py
  airbyte_cdk/sources/streams/concurrent/cursor.py
  airbyte_cdk/sources/streams/concurrent/partition_reader.py
  airbyte_cdk/sources/streams/concurrent/partitions/types.py
  airbyte_cdk/sources/streams/http/http_client.py
  airbyte_cdk/sources/utils/slice_logger.py
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/connector_builder/test_message_grouper.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
  unit_tests/sources/declarative/schema/test_dynamic_schema_loader.py
  unit_tests/sources/declarative/stream_slicers/test_declarative_partition_generator.py
  unit_tests/sources/declarative/test_concurrent_declarative_source.py
  unit_tests/sources/streams/concurrent/scenarios/stream_facade_builder.py
  unit_tests/sources/streams/concurrent/test_concurrent_read_processor.py
  unit_tests/sources/streams/concurrent/test_partition_reader.py
  unit_tests/sources/streams/test_stream_read.py
Labels: bug

#725 fix: monkey patch SQLiteDict in order to fix sqlite3.InterfaceError
  airbyte_cdk/sources/streams/http/http_client.py
  unit_tests/test_requests_cache_monkeypatch_version.py
Labels: bug, security

#702 fix(build): Remove dagger dependencies and replace with uv scripts
  bin/generate-component-manifest-dagger.sh
  bin/generate_component_manifest_files.py
  pyproject.toml
Labels: bug

#733 fix: replace flaky setup-poetry action with install-poetry
  .github/workflows/autofix-command.yml
  .github/workflows/connector-tests.yml
  .github/workflows/pdoc_preview.yml
  .github/workflows/pdoc_publish.yml
  .github/workflows/poetry-lock-command.yml
  .github/workflows/pytest_fast.yml
  .github/workflows/pytest_matrix.yml
  .github/workflows/python_dependency_analysis.yml
  .github/workflows/python_lint.yml
  .github/workflows/test-command.yml
Labels: bug, security

#727 fix(extra_fields): Fix issue with substream partition router picking extra fields
  airbyte_cdk/sources/declarative/partition_routers/cartesian_product_stream_slicer.py
  unit_tests/sources/declarative/partition_routers/helpers.py
  unit_tests/sources/declarative/partition_routers/test_cartesian_product_partition_router.py
  unit_tests/sources/declarative/partition_routers/test_substream_partition_router.py
Labels: bug

#737 fix: update jsonschema constraint to allow 4.20.0+ for fastmcp compatibility
  airbyte_cdk/manifest_server/Dockerfile
  airbyte_cdk/sources/utils/schema_helpers.py
  airbyte_cdk/sources/utils/transform.py
  airbyte_cdk/utils/spec_schema_transformations.py
  poetry.lock
  pyproject.toml
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/sources/utils/test_transform.py
Labels: bug, security

#738 fix(concurrent_declarative_source): set `None` defaults for optional constructor args, remove unnecessary `Generic` implementation
  airbyte_cdk/connector_builder/connector_builder_handler.py
  airbyte_cdk/connector_builder/main.py
  airbyte_cdk/connector_builder/test_reader/reader.py
  airbyte_cdk/manifest_server/command_processor/processor.py
  airbyte_cdk/manifest_server/command_processor/utils.py
  airbyte_cdk/manifest_server/routers/manifest.py
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/yaml_declarative_source.py
  unit_tests/legacy/sources/declarative/test_manifest_declarative_source.py
Labels: bug
