Repository airbytehq/airbyte-python-cdk, pull requests merged in 2025-01, with the labels that each got.

#202 fix(low-code cdk pagination): Fix the offset strategy so that it resets back to 0 when a stream is an incremental data feed
  airbyte_cdk/sources/declarative/requesters/paginators/strategies/offset_increment.py
  airbyte_cdk/sources/declarative/requesters/paginators/strategies/stop_condition.py
  unit_tests/sources/declarative/requesters/paginators/test_default_paginator.py
  unit_tests/sources/declarative/requesters/paginators/test_offset_increment.py
  unit_tests/sources/declarative/requesters/paginators/test_stop_condition.py
Labels: bug

#198 fix(airbyte-cdk): unable to create custom retriever
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
Labels: bug

#194 feat: add `CustomSchemaNormalization`
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/extractors/__init__.py
  airbyte_cdk/sources/declarative/extractors/record_selector.py
  airbyte_cdk/sources/declarative/extractors/type_transformer.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
Labels: enhancement

#208 ci: use binary of airbyte-ci instead of dev version that requires python10
  .github/workflows/connector-tests.yml
Labels: ci

#185 feat(Low-Code Concurrent CDK): Make SimpleRetriever thread-safe so that different partitions can share the same SimpleRetriever
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/requesters/paginators/default_paginator.py
  airbyte_cdk/sources/declarative/requesters/paginators/no_pagination.py
  airbyte_cdk/sources/declarative/requesters/paginators/paginator.py
  airbyte_cdk/sources/declarative/requesters/paginators/strategies/cursor_pagination_strategy.py
  airbyte_cdk/sources/declarative/requesters/paginators/strategies/offset_increment.py
  airbyte_cdk/sources/declarative/requesters/paginators/strategies/page_increment.py
  airbyte_cdk/sources/declarative/requesters/paginators/strategies/pagination_strategy.py
  airbyte_cdk/sources/declarative/requesters/paginators/strategies/stop_condition.py
  airbyte_cdk/sources/declarative/retrievers/async_retriever.py
  airbyte_cdk/sources/declarative/retrievers/simple_retriever.py
  airbyte_cdk/sources/declarative/stream_slicers/declarative_partition_generator.py
  unit_tests/sources/declarative/requesters/paginators/test_cursor_pagination_strategy.py
  unit_tests/sources/declarative/requesters/paginators/test_default_paginator.py
  unit_tests/sources/declarative/requesters/paginators/test_no_paginator.py
  unit_tests/sources/declarative/requesters/paginators/test_offset_increment.py
  unit_tests/sources/declarative/requesters/paginators/test_page_increment.py
  unit_tests/sources/declarative/requesters/paginators/test_stop_condition.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
  unit_tests/sources/declarative/stream_slicers/test_declarative_partition_generator.py
  unit_tests/sources/declarative/test_concurrent_declarative_source.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
Labels: enhancement

#206 feat(low-code): added flatten_lists option to FlattenFields transformation
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/transformations/flatten_fields.py
  unit_tests/sources/declarative/transformations/test_flatten_fields.py
Labels: enhancement

#211 feat: `Async Retriever` add url_requester
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/requesters/README.md
  airbyte_cdk/sources/declarative/requesters/http_job_repository.py
Labels: enhancement

#220 fix: (DeclarativeOAuthFlow) - add the ability to override the `refresh_token_request_body` key names, updated `oauth_connector_input_specification` tooltips
  airbyte_cdk/sources/declarative/auth/oauth.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
  airbyte_cdk/sources/streams/http/requests_native_auth/oauth.py
  unit_tests/sources/streams/http/requests_native_auth/test_requests_native_auth.py
Labels: bug, security, oauth, declarative_oauth, oauth_in_builder

#205 feat(file-based): changes for not mirroring paths
  airbyte_cdk/sources/file_based/config/abstract_file_based_spec.py
  airbyte_cdk/sources/file_based/exceptions.py
  airbyte_cdk/sources/file_based/file_based_source.py
  airbyte_cdk/sources/file_based/file_based_stream_reader.py
  airbyte_cdk/sources/file_based/file_types/unstructured_parser.py
  airbyte_cdk/sources/file_based/stream/default_file_based_stream.py
  unit_tests/sources/file_based/scenarios/csv_scenarios.py
  unit_tests/sources/file_based/stream/test_default_file_based_stream.py
  unit_tests/sources/file_based/test_file_based_stream_reader.py
Labels: enhancement

#166 feat: Add `JsonParser` component to declarative framework
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/decoders/composite_raw_decoder.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  docs/RELEASES.md
  unit_tests/sources/declarative/decoders/test_composite_decoder.py
Labels: enhancement

#219 feat(low-code): pass refresh headers to oauth
  airbyte_cdk/sources/declarative/auth/oauth.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
  airbyte_cdk/sources/streams/http/requests_native_auth/oauth.py
  unit_tests/sources/declarative/auth/test_oauth.py
  unit_tests/sources/streams/http/requests_native_auth/test_requests_native_auth.py
Labels: enhancement, oauth

#223 feat(low-code): add check dynamic stream
  airbyte_cdk/sources/declarative/checks/__init__.py
  airbyte_cdk/sources/declarative/checks/check_dynamic_stream.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/requesters/README.md
  unit_tests/sources/declarative/checks/test_check_dynamic_stream.py
Labels: enhancement

#224 feat(low-code): added condition to TypesMap of DynamicSchemaLoader
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/schema/dynamic_schema_loader.py
  unit_tests/sources/declarative/schema/test_dynamic_schema_loader.py
Labels: enhancement

#169 feat: Adds `ZipfileDecoder` component
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/decoders/__init__.py
  airbyte_cdk/sources/declarative/decoders/zipfile_decoder.py
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/decoders/test_zipfile_decoder.py
Labels: enhancement

#227 feat(low-code): add DpathFlattenFields
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/transformations/dpath_flatten_fields.py
  unit_tests/sources/declarative/transformations/test_dpath_flatten_fields.py
Labels: enhancement

#240 docs: comments on what the `Dockerfile` is for
  Dockerfile
Labels: docs

#174 feat(source-declarative-manifest): add support for custom Python components from dynamic text input
  airbyte_cdk/cli/source_declarative_manifest/_run.py
  airbyte_cdk/connector_builder/connector_builder_handler.py
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/manifest_declarative_source.py
  airbyte_cdk/sources/declarative/parsers/custom_code_compiler.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/test/utils/manifest_only_fixtures.py
  pyproject.toml
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/source_declarative_manifest/resources/source_the_guardian_api/.gitignore
  unit_tests/source_declarative_manifest/resources/source_the_guardian_api/README.md
  unit_tests/source_declarative_manifest/resources/source_the_guardian_api/components.py
  unit_tests/source_declarative_manifest/resources/source_the_guardian_api/components_failing.py
  unit_tests/source_declarative_manifest/resources/source_the_guardian_api/manifest.yaml
  unit_tests/source_declarative_manifest/resources/source_the_guardian_api/valid_config.yaml
  unit_tests/source_declarative_manifest/test_source_declarative_w_custom_components.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
Labels: enhancement

#243 Fix(sdm): module ref issue in python components import
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
Labels: bug

#244 ci: use `ubuntu-24.04` explicitly (resolves CI warnings)
  .github/workflows/connector-tests.yml
  .github/workflows/pdoc_preview.yml
  .github/workflows/pdoc_publish.yml
  .github/workflows/pypi_publish.yml
  .github/workflows/pytest_fast.yml
  .github/workflows/python_lint.yml
  .github/workflows/release_drafter.yml
  .github/workflows/semantic_pr_check.yml
  .github/workflows/slash_command_dispatch.yml
  .github/workflows/test-command.yml
Labels: ci

#234 feat(concurrent cursor): attempt at clamping datetime
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/streams/concurrent/clamping.py
  airbyte_cdk/sources/streams/concurrent/cursor.py
  airbyte_cdk/sources/streams/concurrent/cursor_types.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/streams/concurrent/test_clamping.py
  unit_tests/sources/streams/concurrent/test_cursor.py
Labels: enhancement

#225 fix: handle backoff_strategies in CompositeErrorHandler
  airbyte_cdk/sources/declarative/requesters/error_handlers/composite_error_handler.py
  unit_tests/sources/declarative/requesters/error_handlers/test_composite_error_handler.py
  unit_tests/sources/declarative/requesters/test_http_requester.py
Labels: bug, security

#241 fix: don't mypy unit_tests
  mypy.ini
Labels: bug, security

#111 feat(Low-Code Concurrent CDK): Add ConcurrentPerPartitionCursor
  airbyte_cdk/sources/declarative/concurrent_declarative_source.py
  airbyte_cdk/sources/declarative/extractors/record_filter.py
  airbyte_cdk/sources/declarative/incremental/__init__.py
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  airbyte_cdk/sources/declarative/incremental/global_substream_cursor.py
  airbyte_cdk/sources/declarative/incremental/per_partition_cursor.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/retrievers/simple_retriever.py
  airbyte_cdk/sources/streams/concurrent/cursor.py
  unit_tests/sources/declarative/extractors/test_record_filter.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/retrievers/test_simple_retriever.py
  unit_tests/sources/declarative/test_concurrent_declarative_source.py
Labels: enhancement

#254 fix(airbyte-cdk): Fix RequestOptionsProvider for PerPartitionWithGlobalCursor
  airbyte_cdk/sources/declarative/incremental/per_partition_cursor.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
Labels: bug

#261 fix(low-code): Fix legacy state migration in SubstreamPartitionRouter
  airbyte_cdk/sources/declarative/partition_routers/substream_partition_router.py
  unit_tests/sources/declarative/partition_routers/test_substream_partition_router.py
Labels: bug

#256 feat(low-code): add items and property mappings to dynamic schemas
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/schema/__init__.py
  airbyte_cdk/sources/declarative/schema/dynamic_schema_loader.py
  unit_tests/sources/declarative/schema/test_dynamic_schema_loader.py
Labels: enhancement

#267 fix(low-code): Fix declarative low-code state migration in SubstreamPartitionRouter
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  airbyte_cdk/sources/declarative/partition_routers/substream_partition_router.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
  unit_tests/sources/declarative/partition_routers/test_substream_partition_router.py
Labels: bug

#279 feat(low-code concurrent): Add `use_global_cursor` flag to ConcurrentPerPartitionCursor
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
Labels: enhancement

#288 chore: add missing poetry-core constraint (<2.0), tighten python version constraint (<3.12)
  poetry.lock
  pyproject.toml
Labels: chore

#177 fix(low-code CDK): fix checkpointing for declarative streams
  airbyte_cdk/sources/streams/core.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
  unit_tests/sources/streams/test_stream_read.py
Labels: bug

#292 chore: remove dreprecated `distutils` references
  airbyte_cdk/sources/utils/transform.py
Labels: chore

#293 feat(low-code): add use check availability flag to dynamic check
  airbyte_cdk/sources/declarative/checks/check_dynamic_stream.py
  airbyte_cdk/sources/declarative/declarative_component_schema.yaml
  airbyte_cdk/sources/declarative/models/declarative_component_schema.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  airbyte_cdk/sources/declarative/requesters/error_handlers/http_response_filter.py
  airbyte_cdk/sources/declarative/schema/dynamic_schema_loader.py
  unit_tests/sources/declarative/checks/test_check_dynamic_stream.py
Labels: enhancement

#298 fix(concurrent-partition-cursor): Fix cursor comparison error
  airbyte_cdk/sources/declarative/incremental/concurrent_partition_cursor.py
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/incremental/test_concurrent_perpartitioncursor.py
Labels: bug

#296 fix: make new datetime parse functions properly permissive
  airbyte_cdk/utils/datetime_helpers.py
  unit_tests/utils/test_datetime_helpers.py
Labels: bug, security

#301 feat(low-code): added json.loads to jwt authenticator
  airbyte_cdk/sources/declarative/auth/jwt.py
  unit_tests/sources/declarative/auth/test_jwt.py
Labels: enhancement

#285 fix: (OAuthAuthenticator) - get the `access_token`, `refresh_token`, `expires_in` recursively from `response`
  airbyte_cdk/sources/streams/http/requests_native_auth/abstract_oauth.py
  airbyte_cdk/sources/streams/http/requests_native_auth/oauth.py
  unit_tests/connector_builder/test_connector_builder_handler.py
  unit_tests/sources/streams/http/requests_native_auth/test_requests_native_auth.py
Labels: bug, security, oauth, oauth_in_builder

#304 fix: Relocates `self._extract_slice_fields(stream_slice=stream_slice)` within conditional codeblock that uses it.
  airbyte_cdk/sources/streams/http/http.py
Labels: bug, security

#303 chore: simplify RequestOption construction in component factory
  airbyte_cdk/sources/declarative/parsers/model_to_component_factory.py
  unit_tests/sources/declarative/parsers/test_model_to_component_factory.py
  unit_tests/sources/declarative/test_manifest_declarative_source.py
Labels: chore
